# Generated by Django 3.1.1 on 2020-09-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='creator',
            name='code',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='type',
            name='code',
            field=models.CharField(max_length=2),
        ),
    ]
