# Generated by Django 3.1.1 on 2020-10-04 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201002_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(verbose_name='المقاس')),
                ('quantity', models.IntegerField(verbose_name='الكميه')),
                ('priceIn', models.FloatField(verbose_name='سعر الشراء')),
                ('priceOut', models.FloatField(verbose_name='سعر البيع')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='الصنف')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color', verbose_name='اللون')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.creator', verbose_name='الاسم')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.type', verbose_name='النوع')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
