# Generated by Django 3.1.1 on 2020-10-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201004_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.SlugField(default='dd', max_length=20),
        ),
    ]
