# Generated by Django 3.1.1 on 2020-10-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.SlugField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
