# Generated by Django 3.1.1 on 2020-10-05 09:16

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20201005_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='default.png', upload_to=product.models.image_upload, verbose_name='الصوره'),
        ),
    ]
