# Generated by Django 3.1.1 on 2020-12-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20201005_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='product',
            name='barcode_IMG',
            field=models.ImageField(blank=True, upload_to='Barcodes/', verbose_name='صورة الباركود'),
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
    ]
