# Generated by Django 3.1.1 on 2020-09-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0002_auto_20200930_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='telephone',
            field=models.CharField(max_length=14),
        ),
    ]
