# Generated by Django 3.1.1 on 2020-10-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_auto_20200930_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absense',
            name='dateOut',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
