# Generated by Django 3.1.1 on 2020-10-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0004_auto_20201002_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absense',
            name='dateIn',
        ),
        migrations.RemoveField(
            model_name='absense',
            name='dateOut',
        ),
        migrations.AddField(
            model_name='absense',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absense',
            name='timeIn',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='absense',
            name='timeOut',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
